name: CI
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    name: export pdf resume
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Generate html
        run: npm run export
      - name: Generate PDF
        run: |
          ( npm run start >/dev/null 2>&1 & disown )
          sleep 3
          npm run pdf
      - uses: actions/upload-artifact@v2
        with:
          name: resume.pdf
          path: public/resume.pdf
